#!/usr/bin/env python3
"""Build a MuJoCo MJCF from the xacro-generated Raptor URDF without changing the robot contract.

Kept from the URDF: links, masses, inertias, collision boxes, 10 (or 12 with ankle roll) active + 12 passive joints,
limits, damping/friction. Mirrored from Gazebo tags/world: toe spring stiffness, toe mu 0.8,
default ground mu 1, no self-collision, 1 ms step. Actuators emulate the gz_ros2_control
position path as velocity servos (see raptor_servo.py); this is an approximation, not DART.
"""
import argparse
import hashlib
import xml.etree.ElementTree as ET
from pathlib import Path
import mujoco

ACTIVE = [f'{s}_{j}_joint' for s in ('left', 'right')
          for j in ('hip_roll', 'hip_pitch', 'knee_pitch', 'ankle_pitch', 'ankle_roll')] + ['tail_yaw_joint', 'tail_pitch_joint']
SERVO_KV = 100.  # N*m*s/rad; stiff velocity servo, force-bounded by URDF effort limits.
# Reflected rotor inertia (kg m^2) for the ankle roll only. Its child (pad + toes, ~0.15 kg) is so light
# that the force-limited velocity servo chattered at +-90 rad/s without it (measured 2026-09-29);
# 0.01 ~ a small rotor through a 25:1 gear. Other joints keep 0 so the 10-DOF model is unchanged.
ANKLE_ROLL_ARMATURE = .01


PACKAGES = Path(__file__).resolve().parents[1]/'src'


def build(urdf_text):
    root = ET.fromstring(urdf_text)
    for mesh in root.iter('mesh'):  # collision meshes (e.g. rocker pad); visuals are discarded below
        mesh.set('filename', mesh.get('filename').replace('package://', f'{PACKAGES}/'))
    joints = {j.get('name'): j for j in root.findall('joint')}
    springs = {g.get('reference'): float(g.find('springStiffness').text)
               for g in root.findall('gazebo') if g.find('springStiffness') is not None}
    toe_links = {g.get('reference') for g in root.findall('gazebo') if g.find('mu1') is not None}
    extension = ET.fromstring('<mujoco><compiler discardvisual="true" fusestatic="false" '
                              'balanceinertia="false" angle="radian"/></mujoco>')
    root.insert(0, extension)
    spec = mujoco.MjSpec.from_string(ET.tostring(root, encoding='unicode'))
    spec.modelname = 'raptor'
    spec.option.timestep = .001
    spec.option.integrator = mujoco.mjtIntegrator.mjINT_IMPLICITFAST
    # Pyramidal cone made static standing creep/wobble depending on mu (0.5-1.0); elliptic did not.
    spec.option.cone = mujoco.mjtCone.mjCONE_ELLIPTIC
    world = spec.worldbody
    floor = world.add_geom(name='floor', type=mujoco.mjtGeom.mjGEOM_PLANE, size=[0, 0, .05])
    floor.friction = [1., .005, .0001]
    base_root = spec.body('base_root')
    base_root.add_freejoint(name='floating_base')
    for geom in spec.geoms:
        if geom.name == 'floor':
            continue
        geom.contype, geom.conaffinity = 1, 0  # robot-ground only, like Gazebo self_collide=false
        if geom.parent.name in toe_links:
            geom.friction = [.8, .005, .0001]
            geom.priority = 1  # toe-ground uses toe mu, standing in for DART's min combination
    for name, stiffness in springs.items():
        joint = spec.joint(name)
        joint.stiffness, joint.springref = [stiffness, 0., 0.], 0.
    for name in [n for n in ACTIVE if n in joints]:  # ankle roll only when the URDF has it (12 DOF)
        if 'ankle_roll' in name:
            spec.joint(name).armature = ANKLE_ROLL_ARMATURE
        limit = joints[name].find('limit')
        effort = float(limit.get('effort'))
        actuator = spec.add_actuator(name=name, target=name, trntype=mujoco.mjtTrn.mjTRN_JOINT)
        actuator.set_to_velocity(kv=SERVO_KV)
        actuator.forcelimited = mujoco.mjtLimited.mjLIMITED_TRUE
        actuator.forcerange = [-effort, effort]
        actuator.ctrllimited = mujoco.mjtLimited.mjLIMITED_TRUE
        velocity = float(limit.get('velocity'))
        actuator.ctrlrange = [-velocity, velocity]
    imu = spec.body('base_link').add_site(name='imu', pos=[0, 0, 0])
    spec.add_sensor(name='imu_quat', type=mujoco.mjtSensor.mjSENS_FRAMEQUAT,
                    objtype=mujoco.mjtObj.mjOBJ_SITE, objname=imu.name)
    spec.add_sensor(name='imu_gyro', type=mujoco.mjtSensor.mjSENS_GYRO,
                    objtype=mujoco.mjtObj.mjOBJ_SITE, objname=imu.name)
    spec.compile()
    return spec


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('urdf', type=Path, help='xacro output with passive_toes:=true')
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    text = args.urdf.read_text()
    xml = build(text).to_xml()
    # mesh paths relative to the output file so the model opens on any checkout
    import os
    xml = xml.replace(f'{PACKAGES}/', os.path.relpath(PACKAGES, args.output.resolve().parent)+'/')
    digest = hashlib.sha256(text.encode()).hexdigest()[:16]
    args.output.write_text(f'<!-- Generated by sim/build_model.py from URDF sha256:{digest}. Do not edit. -->\n' + xml)
    print(f'wrote {args.output} (URDF sha256:{digest})')
