controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    raptor_joint_controller:
      type: joint_trajectory_controller/JointTrajectoryController


raptor_joint_controller:
  ros__parameters:
    joints:
      - left_hip_roll_joint
      - left_hip_pitch_joint
      - left_knee_pitch_joint
      - left_ankle_pitch_joint
      - right_hip_roll_joint
      - right_hip_pitch_joint
      - right_knee_pitch_joint
      - right_ankle_pitch_joint
      - tail_yaw_joint
      - tail_pitch_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity
